#cloud-config
runcmd:
  - bash -lc 'set -euxo pipefail
    sudo apt-get update -y
    pip install -U pip "vllm>=0.6" transformers accelerate datasets boto3
    nohup vllm serve meta-llama/Meta-Llama-3.1-8B-Instruct \
      --max-model-len 8192 \
      --gpu-memory-utilization 0.90 \
      --enable-chunked-prefill --enable-prefix-caching \
      --max-num-batched-tokens 32768 \
      --port 8100 > /var/log/vllm_8b.log 2>&1 &
    mkdir -p /opt/ltot/out
  '
